# Generated by Django 6.0.5 on 2026-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
