# Generated by Django 6.0.5 on 2026-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ad_soyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animal_avatar',
            field=models.CharField(choices=[('fox', 'Fennec'), ('owl', 'Baykuş'), ('rabbit', 'Tavşan'), ('cat', 'Kedi')], default='fox', max_length=10),
        ),
    ]
