# Generated by Django 6.0.5 on 2026-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_animal_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_processing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='data_processing_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
